AWSTemplateFormatVersion: '2010-09-09'

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: demo

Outputs:
  Role:
    Value: !GetAtt Repository.RepositoryUri