name: BuildAndDeploy
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16 # https://github.com/aws-actions/configure-aws-credentials
        with:
          role-to-assume: arn:aws:iam::<AwsAccountId>:role/GitHubActionsServiceRole
          role-session-name: MySessionName
          aws-region: us-east-1
      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: DemoEcrRepo
          template: ./template.yml
          capabilities: "CAPABILITY_IAM"
          no-fail-on-empty-changeset: "1"
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: infrastructure
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16 # https://github.com/aws-actions/configure-aws-credentials
        with:
          role-to-assume: arn:aws:iam::<AwsAccountId>:role/GitHubActionsServiceRole
          role-session-name: MySessionName
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: demo3
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG