name: BuildAndDeploy
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  AWS_REGION: us-east-1

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16 # https://github.com/aws-actions/configure-aws-credentials
        with:
          role-to-assume: arn:aws:iam::<AwsAccountId>:role/GitHubActionsServiceRole
          role-session-name: MySessionName
          aws-region: us-east-1
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["docker-compose.yml"]'
      - name: Copy docker-compose to S3
        run: |
          aws s3 cp docker-compose.yml s3://apontem-artifacts